node_env: development
secret_service: UserServiceSecret 
url_db: postgres://postgres:123456@localhost:5432/user_service_db?sslmode=disable
name_service: UserService
port_grpc: 50053
host_grpc: localhost
interval_check: 10s
timeout_check: 10s

db_cache:
  addr: localhost:6379
  db: 1
  password: ""
  max_idle: 10
  max_active: 10
  idle_timeout: 10
  network: tcp

grpc_clients:
    - Name: 'PermissionService'
      ServerAddress: 'localhost:50051'
      MaxRetries: 3
      Time: 20
      Timeout: 15
      PermitWithoutStream: true

permission_service_addr: 'localhost:50051'