migrate-dev-up:
	migrate -path ./migrations -database "postgres://postgres:123456@localhost:5432/userservice_db?sslmode=disable" up

migrate-dev-down:
	migrate -path ./migrations -database "postgres://postgres:123456@localhost:5432/userservice_db?sslmode=disable" down

migrate-dev-reset:
	migrate -path ./migrations -database "postgres://postgres:123456@localhost:5432/userservice_db?sslmode=disable" reset

migrate-dev-drop:
	migrate -path ./migrations -database "postgres://postgres:123456@localhost:5432/userservice_db?sslmode=disable" drop

migrate-dev-create:
	migrate create -ext sql -dir ./migrations -seq $(name)

dev-drop-db:
	docker exec -it postgres_container dropdb --force -U postgres userservice_db

dev-create-db:
	docker exec -it postgres_container createdb -U postgres userservice_db

proto-auth:
	protoc \
		-I . \
		-I C:/Users/a/go/pkg/mod/github.com/envoyproxy/protoc-gen-validate@v1.2.1 \
		--go_out=. --go_opt=paths=source_relative \
		--go-grpc_out=. --go-grpc_opt=paths=source_relative \
		--validate_out=lang=go:. --validate_opt=paths=source_relative \
		proto/auth.proto

build-grpc:
	go build -o bin/grpc-server cmd/gRPC.go

run-grpc:
	go run cmd/gRPC.go

clean:
	rm -f proto/*.pb.go
	rm -f proto/*_grpc.pb.go
	rm -f proto/*.validate.go
		
run:
	go run cmd/main.go